export const DEV_BASEPATH = "http://localhost:5000/api";
export const AUTH_LOGIN_URL = "/auth"
export const AUTH_REGISTER_URL = "/auth/create"
export const AUTH_LOAD_USER_URL = "/auth";
export const PROJECT_CREATE_URL = "/project/create";
export const PROJECT_GET_ALL_URL = "/project/all";
export const FORM_UPDATE_URL = "/form/update";
export const FORM_TOGGLE_PUBLISH_URL ="/form/toggle-publish";
export const FORM_PUBLISH_URL ="/form/publish";
export const FORM_UNPUBLISH_URL ="/form/unpublish";
export const FORM_PREVIEW_URL = "/form/preview";
export const FORM_VIEW_EDITABLE_URL ="/form/view";
export const FORM_GET_URL = "/form";
export const PROJECT_FORM_BUILDER_URL = "/project/form-builder";
export const PROJECTS_URL = "/projects";
export const FORM_SAVE_ANSWER_URL = "/form/answers/save"
export const CLOUDINARY_URL = "https://api.cloudinary.com/v1_1/lundytest/raw/upload"
export const STAGE_ENCODED_ID = "622b28d90acbd7afc84b2ea1";
export const STAGE_COMPLETED_ID = "622b29160acbd7afc84b2ea2";
export const FORMITEM_FIRST_NAME_ID = "6239e4b10a30e1ec69f15bf2";
export const FORMITEM_MIDDLE_NAME_ID = "6239e5d80a30e1ec69f15cd7";
export const FORMITEM_LAST_NAME_ID = "6239e5d80a30e1ec69f15cd6";
export const FORMITEM_GENDER_ID = "6239e5d80a30e1ec69f15cd9";
export const FORMITEM_BIRTHDATE_ID = "6239e5d80a30e1ec69f15cdd";
export const FORMITEM_EMAIL_ID = "6239e6d60a30e1ec69f15d99";
export const MINUTE_MS = 60000;
export const JWTSECRET = "QEnQq52henkMrIa9";
